require('json2ify')
require('es5-shimify')
require('jqueryify')
require('lib/bootstrap.min')
require('lib/bootstrap-button')
require('lib/bootstrap-collapse')
require('lib/bootstrap-dropdown')

require('spine')
require('spine/lib/local')
require('spine/lib/ajax')
require('spine/lib/manager')
require('spine/lib/route')
require('spine/lib/relation')
