language:
    node_js
node_js:
    - 0.8
before_script:
    # install dependencies
    - gem update --system
    - gem install compass
    - npm install -g grunt-cli bower
    - bower install
script:
    - grunt test