# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'coffeescript', :input => 'coffeescripts', :output => 'javascripts/compiled'

guard 'process', :name => 'Combine compiled Javascripts', :command => 'juicer merge -s -f -o javascripts/application.js javascripts/compiled/*/*.js javascripts/compiled/*.js' do
  watch %r{javascripts/compiled/.+\.js}
end

guard 'process', :name => 'Combine library Javascripts', :command => 'juicer merge -s -f -o javascripts/libraries.js javascripts/lib/*.js javascripts/lib/*/*' do
  watch %r{javascripts/lib/.+\.js}
end